name = "haribelajar"
main = "_worker.js"
compatibility_date = "2026-06-01"

# Binding ke KV Namespace
kv_namespaces = [
  { binding = "PROXY_DB", id = "b5b2d4e9ddf44d5382cba7fbac540536" }
]

# Konfigurasi Cron Job untuk auto-sync setiap jam
[triggers]
crons = ["0 * * * *"] # Jalankan setiap jam tepat (menit 0)

[unsafe.metadata.observability]
enabled = true

[observability.logs]
enabled = true